######################################################################################################
# Orion configuration
######################################################################################################
orion: 
  build: 
    version: "2018.06.1"
  properties: 
    type: dev-properties
    version: 1.0 

oauth.server.url: https://websec-int.cable.comcast.com/as/token.oauth2
authServer:
  publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuyHtPtU4wlq70yhZ6RSvuhNSp3TqXaDu2jLnVtGasqV8Iybvgzlx6bWD4wbky9u7g5g8uX/HsCTTse/dhniAnvxWU5PW+jyVUSCN4UX98PSYH2C/QhLrJD6wzQ4CTJxJq7uhfZLkpgJJAl7vr8qLegsYzYg2LC5x/uu7e/QtJfSxmvpGDNyrj3rvWKkodghXWkYQ+qrv7k5vii20pRnnKsN6JfKCTNCVp0Sz5h49ko+x1buTe4dOYpqM067bDk1bgf2kI7MoqJ3e+p9yHgJs+K3BVOKUPPaLBtSMJokGxdyYwND8MltmvCuAmMYhGENuWQpwtca/JotojpPxHxn3rQIDAQAB-----END PUBLIC KEY-----
  scope: orion:orion-dev

######################################################################################################
#Logstash Configuration
######################################################################################################	  
logstash: 
 tcpConfig: 
  hostname: orionlogst-qc-li.ula.comcast.net 
  port: 6000
######################################################################################################
# Application Properties
######################################################################################################
spring: 
 zipkin: 
  enabled: true
  baseUrl: https://zipkin-dev.u1.app.cloud.comcast.net/


DefauiltResponseSize: 50

downstreamname:
  downstreamoperation:
    endpoint: http://localhost:8080/downstreamname/downstreamoperation

######################################################################################################
# Hystrix configuration
######################################################################################################  
hystrix: 
  command: 
    downstreamOperationHystrix: 
      execution: 
        isolation:
          thread: 
            timeoutInMilliseconds: 30000
    
